### ISSUE TITLE
Same named object files get overwritten

### ISSUE THREAD

**Issue by kren1** [travitch/whole-program-llvm#92]
I'm trying to compile ImageMagick with `wllvm`. Among others it has the following 3 source files:

```
../MagickCore/magick.c
../coders/magick.c
../utilities/magick.c
```

However the manifest for `magic.o.bc` objects looks like this:

```
utilities/.magick.o.bc
.magick.o.bc
.magick.o.bc
```
(notice the repeated `.magic.o.bc`) and the symbols defined in `MagicCore/magick.c` are undefined in the final binary.

So I'm pretty sure that `wllvm` puts the `.bc` files for both `coders/magick.c` and `MagicCore/magick.c` into the same `.magic.o.bc` file, so one of them get's overwritten. 

I tried wllvm versions 1.2.2 and 1.2.7 and it seems to happen in both.

Any pointers as to how to fix this?

**Comment by ianamason** [comment]
First try [gllvm](https://github.com/SRI-CSL/gllvm), since I think this was fixed a while ago.
If not I can take a look after thanksgiving.

**Comment by kren1** [comment]
Thanks, I tried it, unfortunately it doesn't solve this issue.

It's slightly different issue than https://github.com/SRI-CSL/gllvm/issues/30 as the two file have the same extension, but are in a different folder. It might be a nastier case, because folders seem to be handled in most cases.

**Comment by ianamason** [comment]
Strange. I will look into this. Sounds like something is suspect with the build system. The bc files should get put next to the o’s. 

Won’t be till next week though. Sorry. 

Did you try using the bitcode store with gllvm?

**Comment by ianamason** [comment]
While you @kren1 are waiting for me, can you add a link to the tarball and the os you are building on?

**Comment by kren1** [comment]
Yeah I agree, the build system must be doing something weird. Thanks for the pointer for the bitcode store! That does indeed resolve the issue! 

I run it on debian 9. 
The magick  build script is something like:

```
 wget -nc "https://imagemagick.org/download/releases/ImageMagick-7.0.8-68.tar.gz" && \
  tar xf ImageMagick-7.0.8-68.tar.gz && \
  cd ImageMagick-7.0.8-68 && \
  sed -i 's/$ac_cv_func_strerror_r_char_p = yes/"x$ac_cv_func_strerror_r_char_p" = xyes/' configure && \
  chmod a+x configure && \
  mkdir obj-bc && cd obj-bc && \
    CC=gclang CFLAGS="-DDEBUG -O1 -Xclang -disable-llvm-passes \
        -D__NO_STRING_INLINES  -D_FORTIFY_SOURCE=0 -U__OPTIMIZE__ -fno-builtin-memcpy"  \
  ../configure --enable-shared=no --disable-openmp --without-threads --without-xml \
      --without-magick-plus-plus --disable-hdri --without-zstd --without-bzlib --without-jbig && \
   CC=glcang make -j5 && \
  find . -executable -type f -exec file '{}' \; | grep ELF | cut -d: -f1 | xargs -n 1 get-bc -m 
```

But you might need some dependencies like libtiff and libpng. Maybe apt installing them is good enough, otherwise I could come up with a docker image.

**Comment by ianamason** [comment]
Have you tried the master of wllvm? 
It lives [here.](https://github.com/SRI-CSL/whole-program-llvm.git)
The paths in the manifest seem to be absolute, so the actual base names 
clashing should not throw a spanner in the works.

**Comment by ianamason** [comment]
I guess I don't really understand the problem. gllvm also uses absolute paths in the
bitcode sections.

Can you show me the manifest you get?

**Comment by kren1** [comment]
It seems this is only happening with debian 9, I upgraded and now it seems fine. Going to close, thanks for your help!
